#主从数据库配置
1spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/task_db?serverTimezone=UTC
      username: root
      password: Caiyi0.0
      driver-class-name: com.mysql.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://172.18.237.231:3307/task_db?serverTimezone=UTC
      username: root   # 只读账户
      password: mysql
      driver-class-name: com.mysql.jdbc.Driver

